spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yanghao?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: yanghao030352
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.yh.model
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml